# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Les Clefs du Succès
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
"Les Clefs du succès offre un service de soutien scolaire spécialisé pour les étudiants scolarisés dans les établissements du système français à Montréal : à savoir le collège Stanislas et le Collège International Marie de France. Avec une expérience dans le tutorat de plus de 15 années, les Clefs du succès offre des programmes variés qui répondent aux besoins de vos enfants allant d’un programme de remise à niveau à un programme d’objectif mention bac et brevet. Des cours de Mathématiques, Physique-chimie et Français sont enseignés ainsi que les cours de complément Québécois."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

collections:
  programmes:
    output: true
    permalink: /:collection/:title
  slides:
    output: true
    permalink: /:collection/:title
  temoignages:
    output: true
    permalink: /:collection/:title


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
