---
new_page_extension: html
auto_deploy: true
admin_path: "/admin"
webhook_url: ''
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _programmes
  label: Programmes
  create: all
  match: "**/*"
- type: directory
  path: _slides
  label: Slides
  create: all
  match: "**/*"
- type: directory
  path: _temoignages
  label: Temoignages
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml}"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
